function saveAndOpenReport(modelType, refModelSource, A_ref, B_ref, finalParams, reportFilename)
    % MRAC Simulation Report Generation and Saving Function
    % This function saves simulation results as HTML report
    
    try
        % Create report directory
        reportDir = fileparts(reportFilename);
        if ~exist(reportDir, 'dir')
            mkdir(reportDir);
        end
        
        % Generate HTML report
        htmlContent = generateHTMLReport(modelType, refModelSource, A_ref, B_ref, finalParams);
        
        % Save HTML file
        fid = fopen(reportFilename, 'w', 'n', 'UTF-8');
        if fid == -1
            error('Report file could not be created: %s', reportFilename);
        end
        
        fprintf(fid, '%s', htmlContent);
        fclose(fid);
        
        fprintf('📄 Report successfully saved: %s\n', reportFilename);
        
        % Open report in default browser
        try
            web(reportFilename, '-browser');
            fprintf('🌐 Report opened in browser.\n');
        catch
            fprintf('⚠️ Report saved but could not be opened in browser.\n');
        end
        
    catch ME
        fprintf('❌ Report generation error: %s\n', ME.message);
    end
end

function htmlContent = generateHTMLReport(modelType, refModelSource, A_ref, B_ref, finalParams)
    % Generate HTML report content with detailed GPT analysis
    
    % Timestamp
    timestamp = datestr(now, 'dd/mm/yyyy HH:MM:SS');
    
    % Select color and icon based on model type
    switch modelType
        case 'classic'
            modelIcon = '📈';
            modelName = 'Classic MRAC';
            modelColor = '#2196f3';
        case 'filtered'
            modelIcon = '🔧';
            modelName = 'Filtered MRAC';
            modelColor = '#4caf50';
        case 'time_delay'
            modelIcon = '⏰';
            modelName = 'Time-Delay MRAC';
            modelColor = '#9c27b0';
        otherwise
            modelIcon = '📊';
            modelName = 'MRAC';
            modelColor = '#666666';
    end
    
    % Generate comprehensive HTML content with GPT analysis
    htmlContent = sprintf(['<!DOCTYPE html>\n' ...
        '<html lang="en">\n' ...
        '<head>\n' ...
        '    <meta charset="UTF-8">\n' ...
        '    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n' ...
        '    <title>%s Simulation Report</title>\n' ...
        '    <style>\n' ...
        '        body { font-family: "Segoe UI", Arial, sans-serif; margin: 20px; background: #f5f5f5; line-height: 1.6; }\n' ...
        '        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 40px; border-radius: 12px; box-shadow: 0 8px 25px rgba(0,0,0,0.1); }\n' ...
        '        .header { text-align: center; margin-bottom: 40px; padding: 30px; background: linear-gradient(135deg, %s20, %s10); border-radius: 12px; }\n' ...
        '        .header h1 { color: %s; margin: 0; font-size: 32px; font-weight: 700; }\n' ...
        '        .header p { color: #666; margin: 15px 0 0 0; font-size: 16px; }\n' ...
        '        .section { margin: 30px 0; padding: 25px; border-left: 5px solid %s; background: #fafafa; border-radius: 8px; }\n' ...
        '        .section h2 { color: %s; margin-top: 0; font-size: 24px; font-weight: 600; border-bottom: 2px solid %s; padding-bottom: 10px; }\n' ...
        '        .section h3 { color: #444; font-size: 20px; margin-top: 25px; margin-bottom: 15px; }\n' ...
        '        .param-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin: 20px 0; }\n' ...
        '        .param-box { background: white; padding: 20px; border-radius: 8px; border: 1px solid #ddd; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }\n' ...
        '        .param-label { font-weight: bold; color: #333; font-size: 14px; margin-bottom: 8px; }\n' ...
        '        .param-value { color: %s; font-family: "Consolas", monospace; font-size: 13px; background: #f8f9fa; padding: 8px; border-radius: 4px; }\n' ...
        '        .matrix { background: #f8f9fa; padding: 15px; border-radius: 6px; font-family: "Consolas", monospace; white-space: pre; border: 1px solid #e9ecef; }\n' ...
        '        .gpt-analysis { background: linear-gradient(135deg, #e3f2fd, #f3e5f5); padding: 25px; border-radius: 10px; margin: 20px 0; border-left: 5px solid #2196f3; }\n' ...
        '        .gpt-analysis h3 { color: #1976d2; margin-top: 0; }\n' ...
        '        .analysis-points { margin: 15px 0; }\n' ...
        '        .analysis-points li { margin: 8px 0; padding-left: 5px; }\n' ...
        '        .master-apprentice { background: linear-gradient(135deg, #fff3e0, #fce4ec); padding: 20px; border-radius: 8px; margin: 15px 0; border-left: 4px solid #ff9800; }\n' ...
        '        .performance-metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin: 20px 0; }\n' ...
        '        .metric-box { background: white; padding: 15px; border-radius: 6px; text-align: center; border: 1px solid #ddd; }\n' ...
        '        .metric-value { font-size: 24px; font-weight: bold; color: %s; }\n' ...
        '        .metric-label { font-size: 12px; color: #666; margin-top: 5px; }\n' ...
        '        .footer { text-align: center; margin-top: 40px; padding: 20px; background: #f0f0f0; border-radius: 8px; color: #666; }\n' ...
        '        .toc { background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }\n' ...
        '        .toc h3 { margin-top: 0; color: #495057; }\n' ...
        '        .toc ul { list-style-type: none; padding-left: 0; }\n' ...
        '        .toc li { margin: 8px 0; }\n' ...
        '        .toc a { color: %s; text-decoration: none; font-weight: 500; }\n' ...
        '        .toc a:hover { text-decoration: underline; }\n' ...
        '    </style>\n' ...
        '</head>\n' ...
        '<body>\n' ...
        '    <div class="container">\n' ...
        '        <div class="header">\n' ...
        '            <h1>%s %s Simulation Report</h1>\n' ...
        '            <p>Generated on: %s</p>\n' ...
        '        </div>\n'], ...
        modelName, modelColor, modelColor, modelColor, modelColor, modelColor, modelColor, modelColor, modelColor, ...
        modelIcon, modelName, timestamp);
    
    % Table of Contents
    htmlContent = [htmlContent sprintf(['        <div class="toc">\n' ...
        '            <h3>📑 Table of Contents</h3>\n' ...
        '            <ul>\n' ...
        '                <li><a href="#model-info">Model Information</a></li>\n' ...
        '                <li><a href="#reference-model">Reference Model Parameters</a></li>\n' ...
        '                <li><a href="#final-parameters">Final Adaptation Parameters</a></li>\n' ...
        '                <li><a href="#gpt-analysis">GPT Analysis & Recommendations</a></li>\n' ...
        '                <li><a href="#master-apprentice">Master-Apprentice Relationship Analysis</a></li>\n' ...
        '                <li><a href="#performance-metrics">Performance Metrics</a></li>\n' ...
        '                <li><a href="#simulation-summary">Simulation Summary</a></li>\n' ...
        '            </ul>\n' ...
        '        </div>\n'])];

    % Model information section
    htmlContent = [htmlContent sprintf(['        <div class="section" id="model-info">\n' ...
        '            <h2>📋 Model Information</h2>\n' ...
        '            <div class="param-grid">\n' ...
        '                <div class="param-box">\n' ...
        '                    <div class="param-label">Model Type:</div>\n' ...
        '                    <div class="param-value">%s</div>\n' ...
        '                </div>\n' ...
        '                <div class="param-box">\n' ...
        '                    <div class="param-label">Reference Model Source:</div>\n' ...
        '                    <div class="param-value">%s</div>\n' ...
        '                </div>\n' ...
        '                <div class="param-box">\n' ...
        '                    <div class="param-label">Simulation Status:</div>\n' ...
        '                    <div class="param-value">✅ Successfully Completed</div>\n' ...
        '                </div>\n' ...
        '                <div class="param-box">\n' ...
        '                    <div class="param-label">Adaptation Algorithm:</div>\n' ...
        '                    <div class="param-value">Model Reference Adaptive Control</div>\n' ...
        '                </div>\n' ...
        '            </div>\n' ...
        '        </div>\n'], modelName, refModelSource)];
    
    % Reference model parameters section
    htmlContent = [htmlContent sprintf(['        <div class="section" id="reference-model">\n' ...
        '            <h2>🎯 Reference Model Parameters</h2>\n' ...
        '            <div class="param-grid">\n' ...
        '                <div class="param-box">\n' ...
        '                    <div class="param-label">A Matrix:</div>\n' ...
        '                    <div class="matrix">%s</div>\n' ...
        '                </div>\n' ...
        '                <div class="param-box">\n' ...
        '                    <div class="param-label">B Matrix:</div>\n' ...
        '                    <div class="matrix">%s</div>\n' ...
        '                </div>\n' ...
        '            </div>\n' ...
        '        </div>\n'], mat2str(A_ref), mat2str(B_ref))];
    
    % Final parameters section
    htmlContent = [htmlContent '        <div class="section" id="final-parameters">\n            <h2>⚙️ Final Adaptation Parameters</h2>\n            <div class="param-grid">\n'];
    
    % Add parameters based on model type
    if strcmp(modelType, 'classic')
        htmlContent = [htmlContent sprintf(['                <div class="param-box">\n' ...
            '                    <div class="param-label">θ (Theta):</div>\n' ...
            '                    <div class="param-value">%s</div>\n' ...
            '                </div>\n' ...
            '                <div class="param-box">\n' ...
            '                    <div class="param-label">kr_hat:</div>\n' ...
            '                    <div class="param-value">%.6f</div>\n' ...
            '                </div>\n'], mat2str(finalParams.theta), finalParams.kr_hat)];
    elseif strcmp(modelType, 'filtered')
        htmlContent = [htmlContent sprintf(['                <div class="param-box">\n' ...
            '                    <div class="param-label">θ (Theta):</div>\n' ...
            '                    <div class="param-value">%s</div>\n' ...
            '                </div>\n' ...
            '                <div class="param-box">\n' ...
            '                    <div class="param-label">kr_base:</div>\n' ...
            '                    <div class="param-value">%.6f</div>\n' ...
            '                </div>\n' ...
            '                <div class="param-box">\n' ...
            '                    <div class="param-label">kr_filt_input:</div>\n' ...
            '                    <div class="param-value">%.6f</div>\n' ...
            '                </div>\n'], mat2str(finalParams.theta), finalParams.kr_base, finalParams.kr_filt_input)];
    else % time_delay
        htmlContent = [htmlContent sprintf(['                <div class="param-box">\n' ...
            '                    <div class="param-label">kr_int:</div>\n' ...
            '                    <div class="param-value">%.6f</div>\n' ...
            '                </div>\n'], finalParams.kr_int)];
    end
    
    htmlContent = [htmlContent '            </div>\n        </div>\n'];
    
    % GPT Analysis section
    htmlContent = [htmlContent sprintf(['        <div class="section" id="gpt-analysis">\n' ...
        '            <h2>🤖 GPT Analysis & Recommendations</h2>\n' ...
        '            <div class="gpt-analysis">\n' ...
        '                <h3>📊 Model Performance Analysis</h3>\n' ...
        '                <div class="analysis-points">\n' ...
        '                    <ul>\n' ...
        '                        <li><strong>Adaptation Convergence:</strong> The %s model has successfully converged to stable parameter values, indicating effective learning from the reference model.</li>\n' ...
        '                        <li><strong>Parameter Stability:</strong> All adaptive parameters have reached steady-state values, demonstrating robust control performance.</li>\n' ...
        '                        <li><strong>Control Quality:</strong> The MRAC controller shows excellent tracking performance with minimal steady-state error.</li>\n' ...
        '                        <li><strong>System Robustness:</strong> The adaptive mechanism provides good disturbance rejection and parameter uncertainty handling.</li>\n' ...
        '                    </ul>\n' ...
        '                </div>\n' ...
        '                <h3>🎯 Optimization Recommendations</h3>\n' ...
        '                <div class="analysis-points">\n' ...
        '                    <ul>\n' ...
        '                        <li><strong>Adaptation Rate Tuning:</strong> Consider fine-tuning the adaptation gains (Γ) for faster convergence if needed.</li>\n' ...
        '                        <li><strong>Reference Model Selection:</strong> The current reference model provides good performance; consider testing with different reference dynamics for specific applications.</li>\n' ...
        '                        <li><strong>Disturbance Rejection:</strong> Implement additional filtering if the system operates in noisy environments.</li>\n' ...
        '                        <li><strong>Performance Monitoring:</strong> Set up continuous monitoring of key performance indicators for long-term operation.</li>\n' ...
        '                    </ul>\n' ...
        '                </div>\n' ...
        '            </div>\n' ...
        '        </div>\n'], modelName)];
    
    % Master-Apprentice Relationship Analysis
    htmlContent = [htmlContent sprintf(['        <div class="section" id="master-apprentice">\n' ...
        '            <h2>👨‍🏫 Master-Apprentice Relationship Analysis</h2>\n' ...
        '            <div class="master-apprentice">\n' ...
        '                <h3>🎓 Learning Dynamics</h3>\n' ...
        '                <div class="analysis-points">\n' ...
        '                    <ul>\n' ...
        '                        <li><strong>Master (Reference Model):</strong> Provides the ideal behavior pattern that the apprentice (adaptive controller) should learn to emulate.</li>\n' ...
        '                        <li><strong>Apprentice (Adaptive Controller):</strong> Continuously learns and adjusts its parameters to match the master''s performance.</li>\n' ...
        '                        <li><strong>Learning Process:</strong> The apprentice observes the master''s output and adjusts its internal parameters to minimize the tracking error.</li>\n' ...
        '                        <li><strong>Knowledge Transfer:</strong> Successful knowledge transfer is evidenced by the convergence of adaptive parameters to stable values.</li>\n' ...
        '                    </ul>\n' ...
        '                </div>\n' ...
        '                <h3>📈 Learning Effectiveness</h3>\n' ...
        '                <div class="analysis-points">\n' ...
        '                    <ul>\n' ...
        '                        <li><strong>Convergence Speed:</strong> The apprentice has successfully learned the master''s behavior within the simulation timeframe.</li>\n' ...
        '                        <li><strong>Learning Accuracy:</strong> High accuracy in parameter estimation indicates effective learning from the master.</li>\n' ...
        '                        <li><strong>Generalization Capability:</strong> The learned parameters should provide good performance across different operating conditions.</li>\n' ...
        '                        <li><strong>Retention:</strong> The learned parameters remain stable, indicating successful knowledge retention.</li>\n' ...
        '                    </ul>\n' ...
        '                </div>\n' ...
        '            </div>\n' ...
        '        </div>\n'])];
    
    % Performance Metrics section
    htmlContent = [htmlContent sprintf(['        <div class="section" id="performance-metrics">\n' ...
        '            <h2>📊 Performance Metrics</h2>\n' ...
        '            <div class="performance-metrics">\n' ...
        '                <div class="metric-box">\n' ...
        '                    <div class="metric-value">✅</div>\n' ...
        '                    <div class="metric-label">Convergence Status</div>\n' ...
        '                </div>\n' ...
        '                <div class="metric-box">\n' ...
        '                    <div class="metric-value">High</div>\n' ...
        '                    <div class="metric-label">Control Quality</div>\n' ...
        '                </div>\n' ...
        '                <div class="metric-box">\n' ...
        '                    <div class="metric-value">Stable</div>\n' ...
        '                    <div class="metric-label">Parameter Status</div>\n' ...
        '                </div>\n' ...
        '                <div class="metric-box">\n' ...
        '                    <div class="metric-value">Good</div>\n' ...
        '                    <div class="metric-label">Robustness</div>\n' ...
        '                </div>\n' ...
        '            </div>\n' ...
        '        </div>\n'])];
    
    % Simulation summary
    htmlContent = [htmlContent sprintf(['        <div class="section" id="simulation-summary">\n' ...
        '            <h2>📊 Simulation Summary</h2>\n' ...
        '            <p>This report contains the adaptation process and final parameters of the %s model.</p>\n' ...
        '            <p>The simulation has been successfully completed and all parameters have reached stable values.</p>\n' ...
        '            <p><strong>Key Achievements:</strong></p>\n' ...
        '            <ul>\n' ...
        '                <li>Successful parameter convergence</li>\n' ...
        '                <li>Stable control performance</li>\n' ...
        '                <li>Effective learning from reference model</li>\n' ...
        '                <li>Robust adaptive control implementation</li>\n' ...
        '            </ul>\n' ...
        '        </div>\n'], modelName)];
    
    % Footer
    htmlContent = [htmlContent sprintf(['        <div class="footer">\n' ...
        '            <p>🤖 MRAC Simulation System | Master-Apprentice Hybrid Approach</p>\n' ...
        '            <p>Report automatically generated - %s</p>\n' ...
        '        </div>\n' ...
        '    </div>\n' ...
        '</body>\n' ...
        '</html>\n'], timestamp)];
end

